// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetFileInfo(arg1:string):Promise<main.FileInfo>;

export function GetStartupFile():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<main.ReadResult>;

export function RegisterAssociations():Promise<boolean|string>;

export function StopWatch():Promise<void>;

export function WatchFile(arg1:string):Promise<void>;
