// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetStartupFile() {
  return window['go']['main']['App']['GetStartupFile']();
}

export function GetSystemFonts() {
  return window['go']['main']['App']['GetSystemFonts']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RegisterAssociations() {
  return window['go']['main']['App']['RegisterAssociations']();
}

export function SetZoomPref(arg1) {
  return window['go']['main']['App']['SetZoomPref'](arg1);
}

export function StopWatch() {
  return window['go']['main']['App']['StopWatch']();
}

export function WatchFile(arg1) {
  return window['go']['main']['App']['WatchFile'](arg1);
}
